### ISSUE TITLE
Fix Body of the New Methods for implementation of KB Interface 

### ISSUE THREAD

**Issue by gulyx** [IASI-LEKS/bedspread#31]
@ftaglino please update the body of this commit : https://github.com/IASI-LEKS/bedspread/pull/30/commits/5444a73c0db0b3d6a81546eb86a5b89736d462b0

Specifically at [Line 194](https://github.com/ftaglino/bedspread/blob/5444a73c0db0b3d6a81546eb86a5b89736d462b0/bedspread-core/src/main/java/it/cnr/iasi/leks/bedspread/rdf/impl/RDFGraph.java#L194)

**Comment by gulyx** [comment]
@ftaglino the previous comment refers to PR #30

**Comment by ftaglino** [comment]
@gulyx the raised point was already fixed

**Comment by gulyx** [comment]
Indeed ... this issue was your a demo for @ftaglino.
Now I close it.
