### ISSUE TITLE
filterCurrentlyActiveNodes

### ISSUE THREAD

**Issue by ftaglino** [IASI-LEKS/bedspread#43]
Think about moving the check (https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/java/it/cnr/iasi/leks/bedspread/AbstractSemanticSpread.java#L142)) at the beginning of the while. #42

**Comment by gulyx** [comment]
mmmm not sure. The configurations of all [these 4 sets](https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/java/it/cnr/iasi/leks/bedspread/AbstractSemanticSpread.java#L45-L48) are quite unstable before [L142](https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/java/it/cnr/iasi/leks/bedspread/AbstractSemanticSpread.java#L142)

**Comment by gulyx** [comment]
... or rather you mean to move it just after [this line](https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/java/it/cnr/iasi/leks/bedspread/AbstractSemanticSpread.java#L113) ?!?!

**Comment by gulyx** [comment]
@ftaglino I understood your point. Agreed.

Waiting for your PR.
