### ISSUE TITLE
Images in FOAF namespace

### ISSUE THREAD

**Issue by gulyx** [IASI-LEKS/bedspread#54]
@ftaglino what's about adding in [blacklist](https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/resources/configDBpediaKB_predicatesBlackList.txt) also the following properties from [FOAF](http://xmlns.com/foaf/spec/) ?

* foaf:depiction
* foaf:depicts
* foaf:img
* foaf:logo
* foaf:thumbnail
* foaf:Image

**Comment by ftaglino** [comment]
@gulyx We are in testing and tuning time, and any movement can be in the right as well as in the wrong direction. Anyway, it sounds reasonable and it is worthy to try :-)

**Comment by ftaglino** [comment]
I do not currently see any additional entry in the blacklist file (https://github.com/IASI-LEKS/bedspread/blob/master/bedspread-core/src/main/resources/configDBpediaKB_predicatesBlackList.txt)

**Comment by gulyx** [comment]
solved by PR #55

**Comment by ftaglino** [comment]
Sorry, but I'm still not a full git citizen.
